FROM golang:1.23.3 AS develop

ARG TARGETOS=linux
ARG TARGETARCH=arm64
ENV TZ=Asia/Tokyo

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./internal ./internal

RUN go install github.com/cosmtrek/air@v1.40.4 && \
	go install github.com/go-delve/delve/cmd/dlv@latest && \
    go install honnef.co/go/tools/cmd/staticcheck@latest && \
    go install github.com/swaggo/swag/cmd/swag@latest

COPY .air.toml ./

CMD ["air", "-c", ".air.toml"]
